
/*
  It should be noted that the action types that are like
  GRIDDLE_FILTER mean that the operation has started.
  Past tense action types mean that the operation
  has completed.
*/

export const GRIDDLE_FILTER = 'GRIDDLE_FILTER';
export const GRIDDLE_FILTERED = 'GRIDDLE_FILTERED';
export const GRIDDLE_FILTER_BY_COLUMN = 'GRIDDLE_FILTER_BY_COLUMN';
export const GRIDDLE_FILTERED_BY_COLUMN = 'GRIDDLE_FILTERED_BY_COLUMN';
export const GRIDDLE_FILTER_BY_ADDITIONAL_COLUMN = 'GRIDDLE_FILTER_BY_ADDITIONAL_COLUMN';
export const GRIDDLE_FILTERED_BY_ADDITIONAL_COLUMN = 'GRIDDLE_FILTERED_BY_ADDITIONAL_COLUMN';
export const GRIDDLE_FILTER_REMOVED = 'GRIDDLE_FILTER_REMOVED';
export const GRIDDLE_SORT = 'GRIDDLE_SORT';
export const GRIDDLE_SORTED = 'GRIDDLE_SORTED';
export const GRIDDLE_SORT_ADDITIONAL = 'GRIDDLE_SORT_ADDITIONAL';
export const GRIDDLE_SORTED_ADDITIONAL = 'GRIDDLE_SORTED_ADDITIONAL';
export const GRIDDLE_LOAD_DATA = 'GRIDDLE_LOAD_DATA';
export const GRIDDLE_LOADED_DATA = 'GRIDDLE_LOADED_DATA';
export const GRIDDLE_NEXT_PAGE = 'GRIDDLE_NEXT_PAGE';
export const GRIDDLE_PREVIOUS_PAGE = 'GRIDDLE_PREVIOUS_PAGE';
export const GRIDDLE_GET_PAGE = 'GRIDDLE_GET_PAGE';
export const GRIDDLE_PAGE_LOADED = 'GRIDDLE_PAGE_LOADED';
export const GRIDDLE_SET_PAGE_SIZE = 'GRIDDLE_SET_PAGE_SIZE';
export const GRIDDLE_INITIALIZE = 'GRIDDLE_INITIALIZE';
export const GRIDDLE_INITIALIZED = 'GRIDDLE_INITIALIZED';
export const GRIDDLE_REMOVED = 'GRIDDLE_REMOVED';
export const GRIDDLE_TOGGLE_COLUMN = 'GRIDDLE_TOGGLE_COLUMN';
export const GRIDDLE_ROW_TOGGLED = 'GRIDDLE_ROW_TOGGLED';
export const GRIDDLE_ROW_SELECTION_TOGGLED = 'GRIDDLE_ROW_SELECTION_TOGGLED';
